python/django_projects/myapps/finances/urls.py
from django.urls import path

from . import views

app_name = 'finances'
urlpatterns = [
    path('', views.index, name='index'),
    path('transactions/view/<int:pk>',
         views.TransactionView.as_view(), name="view_transaction"),
    path('transactions/view', views.TransactionsView.as_view(), name="view"),
    path('transactions/insert', views.TransactionFormView.as_view(), name='insert'),
    path('transactions/insertResult', views.insertResult, name='insertResult'),
]

python/django_projects/myapps/myapps/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('finances/',include('finances.urls'),name='finances'),
    path('admin/', admin.site.urls,name='admin'),
    path('accounts/',include('django.contrib.auth.urls'),name='accounts'),
]

python/django_projects/myapps/finances/models.py
from django.db import models
from django.utils import timezone
from .reference import TYPE_CHOICES
from django.contrib.auth.models import User
# Create your models here.


class Transaction(models.Model):
    date = models.DateField()
    amount = models.FloatField()
    type = models.CharField(
        max_length=2,
        choices=TYPE_CHOICES,
        default='CA'
    )
    description = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return '\"{0}\" for ${1} by {2}'.format(self.description, self.amount, self.user)
# class BalanceEntry(models.Model):
#     transaction = models.ForeignKey(Transaction,on_delete=models.CASCADE)
#     balance =

python/django_projects/myapps/finances/forms.py
from django import forms
from .reference import TYPE_CHOICES

# class TransactionForm(forms.Form):
#     # date = models.DateField()
#     amount = forms.FloatField()
#     type = forms.ChoiceField(
#         choices=TYPE_CHOICES,
#     )
#     description = forms.CharField(max_length=255)

python/django_projects/myapps/finances/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# from .forms import TransactionForm
from .models import Transaction
from .reference import TYPE_CHOICES

# Create your views here.


# view a single transaction
class TransactionView(LoginRequiredMixin, generic.detail.DetailView):
    model = Transaction
    context_object_name = 'transaction'
    template_name = 'finances/viewTransaction.html'
    def dispatch(self,request,*args,**kwargs):
        transaction_user = Transaction.objects.get(pk=kwargs['pk']).user
        if request.user != transaction_user:
            return HttpResponseForbidden('FORBIDDEN: This is not a transaction made by you. You cannot view it')
        else:
            return super().dispatch(request,*args,**kwargs)


# view all of the transactions
class TransactionsView(LoginRequiredMixin, generic.ListView):
    model = Transaction
    context_object_name = 'transactions'
    template_name = 'finances/view.html'
    def get_queryset(self):
        return Transaction.objects.filter(user=self.request.user)


@login_required
def index(request):
    return render(request, 'finances/index.html')


# class TransactionFormView(LoginRequiredMixin, generic.edit.FormView):
#     template_name = 'finances/insert.html'
#     context_object_name = 'form'
#     form_class = TransactionForm
class TransactionFormView(LoginRequiredMixin, generic.edit.CreateView):
    model = Transaction
    fields = ['amount', 'type', 'description']
    template_name = 'finances/insert.html'


@login_required
def insertResult(request):
    amount = request.POST['amount']
    type = request.POST['type']
    user = request.user
    context_type = ''
    for pair in TYPE_CHOICES:
        if pair[0] == type:
            context_type = pair[1]
            break
    description = request.POST['description']
    context = {'amount': amount, 'type': context_type,
               'description': description}
    transaction = Transaction.objects.create(
        date=timezone.now(), amount=amount, type=type, description=description, user=user)
    pk = transaction.id
    return HttpResponseRedirect(reverse('finances:view_transaction', args=[pk]))

python/django_projects/myapps/myapps/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request,'myapps/index.html')

python/django_projects/myapps/finances/templates/finances/base.html
{% extends 'base.html' %}
{% block nav %}
<nav>
    <div class="nav-wrapper teal">
        <a href="{% url 'finances:index' %}" class="brand-logo">Finances</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'finances:view' %}">view all</a></li>
            <li><a href="{% url 'finances:insert' %}">Insert</a></li>
            <li><a href="/accounts/logout">Logged in as {{ user }}. Log Out</a></li>
        </ul>
    </div>
</nav>
{% endblock %}
{% block base_content %}
<h1>TODO: make model include user ForeignKey and only have that user's transactions show up</h1>
<div class="content container">
    {% block content %} {% endblock %}
</div>
{% endblock %}

python/django_projects/myapps/finances/templates/finances/index.html
{% extends 'finances/base.html' %}
{% block content %}
<h3>Welcome to the finances app. Here, you can add transactions to your database and view a list of them</h3>
{% endblock %}

python/django_projects/myapps/finances/templates/finances/insert.html
{% extends 'finances/base.html' %}
{% block content %}
<form action="{% url 'finances:insertResult' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn" value="Submit" />
</form>
{% endblock %}

python/django_projects/myapps/finances/templates/finances/login.html
{% extends 'finances/base.html' %}
{% block content %}
<form class="" action="" method="post">
  
</form>
{% endblock %}

python/django_projects/myapps/finances/templates/finances/view.html
{% extends 'finances/base.html' %}
{% block content %}
<title>View Transactions</title>
<table class="responsive-table highlight card-panel">
  <thead>
    <tr>
      <th>Description</th>
      <th>Amount</th>
      <th>Type</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    {% for transaction in transactions %}
    <tr onclick="window.location='{% url 'finances:view_transaction' transaction.id %}';">
      <td>{{ transaction.description }}</td>
      <td>{{ transaction.amount }}</td>
      <td>{{ transaction.type }}</td>
      <td>{{ transaction.date }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

python/django_projects/myapps/finances/templates/finances/viewTransaction.html
{% extends 'finances/base.html' %}
{% block content %}
<title>View a Transaction</title>
<table class="responsive-table highlight">
  <thead>
    <tr>
      <th>Description</th>
      <th>Amount</th>
      <th>Type</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{ transaction.description }}</td>
      <td>{{ transaction.amount }}</td>
      <td>{{ transaction.type }}</td>
      <td>{{ transaction.date }}</td>
    </tr>
  </tbody>
</table>
{% endblock %}

python/django_projects/myapps/myapps/templates/myapps/base.html
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script type="text/javascript">
  $('document').ready(() => $('select').material_select())
</script>

<body>
  <div class="content container">
    <div class="page-header">
      <h1>myapps</h1>
    </div>
    <div class="content container">
      {% block content %}
      {% endblock %}
    </div>
  </div>
</body>

python/django_projects/myapps/myapps/templates/myapps/index.html
{% extends 'myapps/base.html' %}
{% block content %}
<h3>apps:</h3>
<ul class="collection">
  <li class="collection-item"><b><a href="finances/">finances</a></b><br>
  finances is a django web app that has a user enter transactions (expenses, getting paid, deposits, withdrawals) and a database keeps track of them</li>
</ul>
{% endblock %}

python/django_projects/myapps/templates/base.html
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
<script type="text/javascript">
  $('document').ready(() => $('select').material_select())
</script>
<body>
  {% block nav %}{% endblock %}
  <div class="content container">
    {% block base_content %}
    {% endblock %}
  </div>
</body>