python/django_projects/friendsAndEnemies/app/urls.py
from django.urls import path,include
from . import views
app_name = 'app'
urlpatterns = [
    path('',views.index,name='index'),
    path('get_input/',views.get_input,name='get_input')
]

python/django_projects/friendsAndEnemies/friendsAndEnemies/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls'))
]

python/django_projects/friendsAndEnemies/app/models.py
from django.db import models

# Create your models here.

python/django_projects/friendsAndEnemies/app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .process import generate_teams
# Create your views here.
def index(request):
    return render(request,'app/input.html')
def get_input(request):
    obj = request.POST
    players, friends, enemies = obj['players'],obj['friends'],obj['enemies']
    output = generate_teams(players,enemies,friends)
    return HttpResponse(output)

python/django_projects/friendsAndEnemies/app/templates/app/input.html
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
<div class="container">
    <form action="{% url 'app:get_input' %}" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="input-field">
          <textarea id="players" class="materialize-textarea" name="players"></textarea>
          <label for="players">players separated by commas</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field">
          <textarea id="friends" class="materialize-textarea" name="friends"></textarea>
          <label for="friends">friend pairs separated by commas and newlines</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field">
          <textarea id="enemies" class="materialize-textarea" name="enemies"></textarea>
          <label for="enemies">enemy pairs separated by commas and newlines</label>
        </div>
      </div>
      <input type="submit" class="btn" value="submit">
    </form>
</div>